### ISSUE TITLE
Syntax error in Python 3.7

### ISSUE THREAD

**Issue by fabiommendes** [pinax/pinax-badges#27]
badges/base.py uses a variable named "async" which is now a syntax error in Python 3.7.  We should change it to async_ or some other name that does not conflict with the grammar.

**Comment by KatherineMichel** [comment]
@fabiommendes Hi Fabio. Thank you for bringing this to our attention. Would you be willing to submit a PR for this?

**Comment by fabiommendes** [comment]
No problem. I sent a PR at https://github.com/pinax/pinax-badges/pull/30. Closing the issue :)

**Comment by BarrensZeppelin** [comment]
Can you publish the new version to PyPi? :)

**Comment by longhotsummer** [comment]
Hi - please can you publish to PyPi for projects using 3.7.

**Comment by KatherineMichel** [comment]
I've requested the credentials to publish to PyPi and will go ahead and do it if/when I get the credentials. @BarrensZeppelin @longhotsummer

**Comment by longhotsummer** [comment]
Hi @KatherineMichel - any update on pushing to pypi?

**Comment by KatherineMichel** [comment]
@longhotsummer I've asked again for access. Hopefully will receive. But in the meantime, you can pip install directly from GitHub, if that helps. https://pip.pypa.io/en/stable/reference/pip_install/#git

**Comment by longhotsummer** [comment]
Hi @KatherineMichel any update on access?

**Comment by KatherineMichel** [comment]
@fabiommendes @BarrensZeppelin @longhotsummer I got access today and created a release on GitHub and PyPI. Again, sorry for the delay. I added Python 3.7 testing support as well. Hope it works for you all. If you have any problems, let me know. I want to add a GitHub Action to all of the pinax apps included in our next major release so that we can automatically publish.  https://pypi.org/project/pinax-badges/2.0.3/
