### ISSUE TITLE
'bool' object is not callable

### ISSUE THREAD

**Issue by anjunamonkey** [pinax/pinax-badges#37]
Receiving an error 'bool' object is not callable with Django 3.

Believe that if request.user.is_authenticated(): needs to be updated to  
if request.user.is_authenticated:

**Comment by KatherineMichel** [comment]
@anjunamonkey That's probably because this app has not yet been updated to support Django 3.0. We have a release plan with info about contributing, if you'd like to update it. Otherwise, hopefully it will be done soon. https://github.com/pinax/pinax/wiki/Pinax-20.XX-Release-Plan#app-updates--must-have

**Comment by KatherineMichel** [comment]
I missed this when I initially dropped Python 2.7 support, but it's fixed now. It should be published soon. https://github.com/pinax/pinax-badges/commit/37c85102a94a069bb5a79e6d13a7ac3124b2737c#diff-19e0918eb9dc21e751077625224ec952
